SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
SCREEN_TITLE = "Last Flight Home"

PLAYER_SPEED = 5
PLAYER_ROTATION_SPEED = 3

START_FUEL = 1000
START_HEALTH = 100

FUEL_CONSUMPTION = 0.2  # топлива за кадр движения

